### PR TITLE
Update Kubernetes to v1.8.0

### PR DESCRIPTION
**Pull request by Random-Liu**
Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
@mikebrow Will do. 1.8.0 is not out yet in last PR. :)

**Comment by Random-Liu** [comment]
@mikebrow Done

**Comment by abhi** [comment]
LGTM if no changes in kubernetes vendoring

**Comment by Random-Liu** [comment]
@abhi No changes, verified. :)

@mikebrow I've updated your comment. Will merge ahead. :)

**Pull request merged**
