### PR TITLE
Putting in the go versions we want to test against

### PR DESCRIPTION
**Pull request by mikebrow**
Fixing the go versions being tested against after the last travis PR introducing stages.

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by mikebrow** [comment]
And there's a bug with stages where you can't matrix in multiple go versions.. great. I'll push a different fix.

**Comment by mikebrow** [comment]
So the trick with this beta stages tool and the matrix feature seems to be to create your own matrix of stages by hand for the various combinations you want.  Since we had two go versions to test against both stages that doubles the number of stages, but they have the same name so it looks correct in the travis log. If / when they fix this, we can go back to the old go matrix style. Apparently half the conversation around this beta feature is about this particular issue... https://github.com/travis-ci/beta-features/issues/11#issuecomment-301875447

**Comment by Random-Liu** [comment]
@mikebrow Actually, I'm fine with only build with 1.8, which is also what containerd doing.

**Comment by mikebrow** [comment]
They are testing 1.8.x which is currently v1.8.3. We are testing v1.8 now. Pretty much all of the incubator projects are testing against 1.8.3 and tip. The value of tip is to make sure we don't enter any changes that will become incompatible with future releases of go.. and to aid in forcing golang to generate future releases that are compatible with prior ones..

**Comment by mikebrow** [comment]
That worked.. going to try to add stage scripts so there's less copying

**Comment by mikebrow** [comment]
I like it... @Random-Liu what do you think?

**Comment by Random-Liu** [comment]
@mikebrow Different stages will run in serial, previously the test only took 11min, but with this change it takes 26min. 

According to the document https://docs.travis-ci.com/user/build-stages/, you should change it to:
```
    - stage: Build
      script: ./hack/travis-build.sh
      go: 1.8.x
    - script: ./hack/travis-build.sh
      go: tip
    - stage: Test
      script: ./hack/travis-test.sh
      go: 1.8.x
    - script: ./hack/travis-test.sh
      go: tip
```

And after changing to `./hack/travis-test.sh`, it's hard to figure out what commands are running, I kind of prefer the previous solution.

**Comment by mikebrow** [comment]
Agreed. Updated per comments and offline discussion.

**Comment by mikebrow** [comment]
Per discussion streamlined the two stages into Verify; and Build and Test

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
