### PR TITLE
Boilerplate test

### PR DESCRIPTION
**Pull request by mikebrow**
git subtree add for kubernetes/repro-infra...

Added boilerplate testing to make verify

Cleaned up some boilerplate text on a  few files...

Closes issue #11

### CODE REVIEW

**Comment by mikebrow** [comment]
@Random-Liu ready to review.. I like the boilerplate test it works good.

**Comment by Random-Liu** [comment]
@mikebrow LGTM.

* On one hand, it still feels weird that we add `repo-infra` as sub-tree, but removed part of it.
* On the other hand, we'll have duplicated files if we don't remove the extra files `gofmt`, `govet` etc.

Let's keep it like this way today, and vendor the whole `repo-infra` when it meets our requirement.

**Comment by Random-Liu** [comment]
Filed an issue for this, and let's get this merged after squash. https://github.com/kubernetes-incubator/cri-containerd/issues/15

**Comment by Random-Liu** [comment]
Offline discussed with @mikebrow, the commits are from the subtree. Then this PR is good to go after test passes.

**Comment by Random-Liu** [comment]
Close and re-open to trigger the test.

**Comment by mikebrow** [comment]
All commits signed.  DCO check was confused.

**Comment by Random-Liu** [comment]
@mikebrow The test still fails. I re-triggered the test. And let's see.

**Pull request merged**
