### PR TITLE
Add container logging support.

### PR DESCRIPTION
**Pull request by Random-Liu**
Based on #53, #52 and #48. Only the last 2 commits are new.

This PR added container logging support.

### CODE REVIEW

**Comment by Random-Liu** [comment]
With this PR, we could pass more CRI validation test now:
```
Summarizing 14 Failures:

[Fail] [k8s.io] Security Context runtime should support container with security context [It] runtime should support setting Capability 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:252

[Fail] [k8s.io] Networking runtime should support networking [It] runtime should support port mapping with host port and container port [Conformance] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/networking.go:206

[Fail] [k8s.io] Security Context runtime should support NamespaceOption in the Security Context [It] runtime should support HostIpc is false [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:315

[Fail] [k8s.io] Security Context runtime should support NamespaceOption in the Security Context [It] runtime should support HostIpc is true [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:315

[Fail] [k8s.io] Security Context runtime should support container with security context [It] runtime should support Privileged is true [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:539

[Fail] [k8s.io] Security Context runtime should support NamespaceOption in the Security Context [It] runtime should support HostNetwork is true [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:603

[Fail] [k8s.io] Networking runtime should support networking [It] runtime should support DNS config [Conformance] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/networking.go:165

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support portforward [Conformance] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:231

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support exec [Conformance] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:127

[Fail] [k8s.io] Streaming runtime should support streaming interfaces [It] runtime should support attach [Conformance] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:183

[Fail] [k8s.io] Security Context runtime should support container with security context [It] runtime should support RunAsUser [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:315

[Fail] [k8s.io] Security Context runtime should support NamespaceOption in the Security Context [It] runtime should support HostPID [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/util.go:214

[Fail] [k8s.io] Security Context runtime should support container with security context [It] runtime should support RunAsUserName [security context] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:315

[Fail] [k8s.io] Container runtime should support basic operations on container [It] runtime should support execSync [Conformance] 
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:315

Ran 36 of 36 Specs in 150.726 seconds
FAIL! -- 22 Passed | 14 Failed | 0 Pending | 0 Skipped --- FAIL: TestE2ECRI (150.73s)
FAIL

Ginkgo ran 1 suite in 2m30.796156486s
Test Suite Failed
exit status 1
```

Most failures are expected, I'll add `execSync` soon to help run more test.

One weird thing is that network is not working. @xlgao-zju

**Comment by Random-Liu** [comment]
@xlgao-zju OK. It's working.

The host network and host port is not working.

Host port not working is expected, but host network should work. Will take a look.

**Comment by Random-Liu** [comment]
Fixed the code, and `Hostnetwork` test also passed now.

**Comment by mikebrow** [comment]
Which version of containerd are you using to get these success rates? I'm on containerd 2562aca per the recent move up on master.

**Comment by Random-Liu** [comment]
Will rebase and merge this PR. But we should be aware of that after switching to the new containerd client:
1) We'll still need the cri log format decorating logic;
2) We'll not need the agent factory because in the containerd client, because the routine creation logic with be in `WithXXX` functions, and will not run in mock client.

**Pull request merged**
