### PR TITLE
Create host path is mount source does not exist.

### PR DESCRIPTION
**Pull request by Random-Liu**
Docker is doing this. And Kubelet is replying on this behavior.

Ref https://github.com/kubernetes/kubernetes/issues/52318.

/cc @abhinandanpb 

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by abhinandanpb** [comment]
LGTM. This fixes the issues seen on the installer

**Comment by Random-Liu** [comment]
@abhinandanpb I've manually tested this PR, and it works. Will merge after the test passes.

**Comment by miaoyq** [comment]
If so, it is necessary to check the propagation of the host path.

**Comment by Random-Liu** [comment]
@miaoyq Please also fix this in #230. I'll have to review your PR later. Have a demo on Thursday. :)

**Comment by Random-Liu** [comment]
I sent another commit to avoid using `go get` to clone dependency repos.

CNI HEAD is broken now, using `go get` will try to build it and cause an error. The new commit use `git clone` instead.

**Comment by Random-Liu** [comment]
Filed an CNI PR for the compile failure https://github.com/containernetworking/plugins/pull/73

**Comment by miaoyq** [comment]
@Random-Liu  OK, I will.

**Pull request merged**
