### PR TITLE
Quick typo fix for README.md

### PR DESCRIPTION
**Pull request by mhamrah**

### CODE REVIEW

**Comment by mhamrah** [comment]
signed cla

**Comment by Random-Liu** [comment]
LGTM

**Comment by mikebrow** [comment]
If first time setting up signatures for github... Set user.* entries to global and/or local:
```
$ git config --local user.name "Full name here"

$ git config --local user.email "email address here"
Or:
$ git config --global user.name "Full name here"

$ git config --global user.email "email address here"
```
Then when you sign a commit git commit -s 

Since the commit is already sent:
git commit -s --amend
then re-push
git commit push -f origin patch-1

Cheers...

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
