### PR TITLE
Update 'hack/versions'

### PR DESCRIPTION
**Pull request by miaoyq**
/cc @Random-Liu 

Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>

### CODE REVIEW

**Comment by Random-Liu** [comment]
@miaoyq You didn't update other Kubernetes repo correspondingly in your last PR. Could you do that in this PR?

Just check what is the date of the Kubernetes commit we are using. And find latest commit for the other repo on that day.

**Comment by miaoyq** [comment]
@Random-Liu  OK, I will update them now.

**Comment by miaoyq** [comment]
@Random-Liu Updated.

**Pull request merged**
