### PR TITLE
contrib instead of contib

### PR DESCRIPTION
**Pull request by antony360**
Replaced error on Ansible README.

### CODE REVIEW

**Comment by Random-Liu** [comment]
oops. Thanks!
Can you sign your commit? `git commit --amend -s`.

LGTM

**Comment by mikebrow** [comment]
@antony360 Your DCO is invalid. Have you signed the CLA?

**Comment by antony360** [comment]
@mikebrow Where do you see that my DCO is invalid ? It seems like it's ok since I can see "antony360 authorized" on CLA check. TY

**Comment by mikebrow** [comment]
https://travis-ci.org/kubernetes-incubator/cri-containerd/jobs/306055003#L679-L680

**Comment by antony360** [comment]
@mikebrow It works now, the problem came from the fact that the commit was not signed with the same email address as the author.
TY

**Comment by jbguerraz** [comment]
qsef

**Pull request merged**
