### PR TITLE
add lease for importer

### LINKED ISSUE #389: Use `lease` in image load.
Containerd is adding a new `lease` api. We should use it in our image load instead of `gc.root` after that is merged.

https://github.com/containerd/containerd/pull/1690

### PR DESCRIPTION
**Pull request by yanxuean**
fix #389
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

### CODE REVIEW

**Comment by yanxuean** [comment]
@Random-Liu   PTAL
Seem like it is unnecessary to add Lease for createImageReference in LoadImage. Because the imagestore has referenced  manifest by repotag.

**Comment by yanxuean** [comment]
/assign @Random-Liu @mikebrow 
PTAL

**Comment by Random-Liu** [comment]
@yanxuean There is a `vet` error: `pkg/containerd/importer/importer.go:80:12:warning: error return value not checked (defer done()) (errcheck)`

**Comment by yanxuean** [comment]
@Random-Liu  done.
The result is too late.

**Pull request merged**
