### PR TITLE
Update cri-containerd version to 1.0.0-alpha.1 in ansible.

### PR DESCRIPTION
**Pull request by Random-Liu**
Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Comment by miaoyq** [comment]
@Random-Liu  I think we should add a `cri_containerd_release_version` for centOS. 
I deployed the `cri-container` on my centOS via ansible,  but it didn't work because of not supporting apparmor.

**Comment by Random-Liu** [comment]
The test failure is caused by a containerd issue. 

/test pull-cri-containerd-node-e2e

**Comment by Random-Liu** [comment]
> I deployed the cri-container on my centOS via ansible, but it didn't work because of not supporting apparmor.

Hm? What is the error? I thought it should work on node without apparmor.

**Comment by miaoyq** [comment]
@Random-Liu Error while loading shared libraries: libapparmor.so.1
```
Oct 16 15:02:34 localhost systemd: cri-containerd.service: main process exited, code=exited, status=127/n/a
Oct 16 15:02:34 localhost cri-containerd: /usr/local/bin/cri-containerd: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
Oct 16 15:02:34 localhost systemd: Unit cri-containerd.service entered failed state.
Oct 16 15:02:34 localhost systemd: cri-containerd.service failed.
```

**Pull request merged**
