### PR TITLE
add debug log for rootfs-not-ready

### PR DESCRIPTION
**Pull request by yanxuean**
Signed-off-by: yason <yan.xuean@zte.com.cn>

We should also modify containerd's diff.Apply.

### CODE REVIEW

**Comment by yanxuean** [comment]
We should also modify diff.Apply in containerd.

**Comment by Random-Liu** [comment]
@yanxuean I don't think it's our `unmount` fails. It is the unmount in containerd fails, it cleans up the snapshot unexpectedly.

IIUC, our removeall will only cleanup the top layer (writable layer), which is fine.

**Comment by yanxuean** [comment]
Yes, we need to modify it in containerd. 
My main thought is printing the "mounts" got from snapshotter.Mounts in checkSnapshot.
It will verify if the parent snapshot is exist.

But Now I think we don't need it again. Because we has been congratulating the 1785 was solve.

**Comment by yanxuean** [comment]
I will close it.

**Comment by yanxuean** [comment]
@Random-Liu  Will we revert the commit about checkSnapshot?  If not I suggest to print the  mounts.

**Comment by yanxuean** [comment]
The checkSnapshot has been reverted. #473 .  Close this.

**Pull request closed without merging**
