### PR TITLE
return without error when stop nonexist sandbox.

### PR DESCRIPTION
**Pull request by sak0**
return without error when stop non-existent sandbox.

Signed-off-by: CuiHaozhi <cuihz@wise2c.com>

### CODE REVIEW

**Comment by Random-Liu** [comment]
I think this is expected behavior. :)

**Comment by sak0** [comment]
@Random-Liu Thanks for review.
I'm not very sure for this ,PTAL
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L28-L32

**Comment by Random-Liu** [comment]
```
    // StopPodSandbox stops any running process that is part of the sandbox and
    // reclaims network resources (e.g., IP addresses) allocated to the sandbox.
    // If there are any running containers in the sandbox, they must be forcibly
    // terminated.
    // This call is idempotent, and must not return an error if all relevant
    // resources have already been reclaimed. kubelet will call StopPodSandbox
    // at least once before calling RemovePodSandbox. It will also attempt to
    // reclaim resources eagerly, as soon as a sandbox is not needed. Hence,
    // multiple StopPodSandbox calls are expected.
```
Yeah, `StopPodSandbox` won't return error if network namespace is already removed, or sandbox container is removed, which follows `must not return an error if all relevant resources have already been reclaimed`. It doesn't mean that i should not return error when sandbox does not exist. :)

Thanks a lot for sending the PR anyway!

**Comment by sak0** [comment]
i got it, thanks :)

**Pull request closed without merging**
