### PR TITLE
Add Sandbox and Container annotatinos

### PR DESCRIPTION
**Pull request by jcvenegas**
Add OCI annotations to help Virtual Machine rutimes to know if will crate a sandbox (VM) or a container (container inside Sandbox (VM).).

### CODE REVIEW

**Comment by mikebrow** [comment]
wave :-) how goes?

**Comment by Random-Liu** [comment]
@jcvenegas Hi, why did you close this PR? :)

**Comment by jcvenegas** [comment]
Hi @mikebrow @Random-Liu , I am reworking some missing parts, I will repoen it when it is ready :)

**Comment by Random-Liu** [comment]
@jcvenegas I see. Thanks for contributing! Will wait for your new PR. :)

**Pull request closed without merging**
